# Generated by Django 4.2.4 on 2023-12-08 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id_categorie', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(default='prenom_user', max_length=100)),
                ('num_tel', models.IntegerField(default=0)),
                ('adresse', models.CharField(default='adresse', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('etat', models.CharField(default='active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id_fournisseur', models.AutoField(primary_key=True, serialize=False)),
                ('nom_enterprise', models.CharField(max_length=100)),
                ('num_tel', models.IntegerField(default=0)),
                ('adresse', models.CharField(default='adresse', max_length=100)),
                ('description', models.TextField()),
                ('id_email', models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='produits_app.compte')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id_produit', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('prix', models.FloatField()),
                ('emplacement', models.CharField(max_length=100)),
                ('date_publication', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='prouits_app/static/images')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits_app.categorie')),
                ('id_fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits_app.fournisseur')),
            ],
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='produits',
            field=models.ManyToManyField(to='produits_app.produit'),
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id_commentaire', models.AutoField(primary_key=True, serialize=False)),
                ('texte_commentaire', models.TextField()),
                ('evaluation', models.PositiveIntegerField()),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits_app.client')),
                ('id_produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits_app.produit')),
            ],
        ),
        migrations.CreateModel(
            name='CommandeProduit',
            fields=[
                ('id_commande', models.AutoField(primary_key=True, serialize=False)),
                ('date_commande', models.DateField()),
                ('statut_commande', models.CharField(max_length=50)),
                ('id_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits_app.client')),
                ('produits', models.ManyToManyField(to='produits_app.produit')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='historique_commandes',
            field=models.ManyToManyField(to='produits_app.commandeproduit'),
        ),
        migrations.AddField(
            model_name='client',
            name='id_email',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='produits_app.compte'),
        ),
    ]
