# Generated by Django 4.2.4 on 2023-12-08 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produits_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id_email',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='id_email',
        ),
    ]
