# Generated by Django 4.2.4 on 2023-12-08 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produits_app', '0002_remove_client_id_email_remove_fournisseur_id_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='id_email',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='produits_app.compte'),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='id_email',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='produits_app.compte'),
        ),
    ]
