# Generated by Django 4.2.6 on 2023-12-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits_app', '0010_panier_quantite'),
    ]

    operations = [
        migrations.AddField(
            model_name='compte',
            name='image',
            field=models.ImageField(default='produits_app/static/images/default_image.png', upload_to='produits_app/static/images/'),
        ),
    ]
