# Generated by Django 4.2.6 on 2023-12-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits_app', '0011_compte_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='image',
            field=models.ImageField(upload_to='produits_app/static/images/'),
        ),
    ]
