# Generated by Django 4.2.6 on 2024-01-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits_app', '0014_alter_compte_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='image',
            field=models.ImageField(default='produits_app/static/images/default_image.png', upload_to='produits_app/static/images/'),
        ),
        migrations.AlterField(
            model_name='panier',
            name='quantite',
            field=models.JSONField(default=dict),
        ),
    ]
