# Generated by Django 4.2.6 on 2024-01-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits_app', '0017_alter_panier_quantite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandeproduit',
            name='date_commande',
            field=models.DateField(auto_now_add=True),
        ),
    ]
