# Generated by Django 4.2.6 on 2024-01-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits_app', '0018_alter_commandeproduit_date_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commandeproduit',
            name='date_commande',
            field=models.DateField(),
        ),
    ]
