# Generated by Django 4.2.6 on 2024-01-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits_app', '0019_alter_commandeproduit_date_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='historique',
            field=models.ManyToManyField(blank=True, to='produits_app.commandeproduit'),
        ),
    ]
