# Generated by Django 4.2.6 on 2024-01-05 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits_app', '0020_alter_client_historique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='image',
            field=models.ImageField(upload_to='produits_app/static/images/'),
        ),
    ]
