# Generated by Django 4.2.6 on 2024-01-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produits_app', '0023_alter_fournisseur_produits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compte',
            name='image',
            field=models.ImageField(upload_to='produits_app/static/images/'),
        ),
    ]
