# Generated by Django 4.2.6 on 2024-01-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("produits_app", "0025_alter_panier_date_expiration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="panier",
            name="date_expiration",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
