# Generated by Django 4.2.6 on 2024-01-09 21:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("produits_app", "0025_alter_compte_image"),
        ("produits_app", "0026_alter_panier_date_expiration"),
    ]

    operations = []
